"""Final commit and branch decisions."""

from __future__ import annotations

from pathlib import Path

from forge.loop.task import TaskPacket
from forge.worktrees.manager import run_git


def commit_approved_work(worktree: Path, task: TaskPacket) -> str:
    run_git(worktree, ["add", "-A"])
    diff_check = run_git(worktree, ["diff", "--cached", "--quiet"], check=False)
    if diff_check.returncode == 0:
        raise RuntimeError("no staged changes to commit")
    message = _commit_message(task.title)
    run_git(
        worktree,
        [
            "commit",
            "-m",
            message,
            "-m",
            "Generated by Forge autonomous branch factory after deterministic gates and council review.",
        ],
        timeout=180.0,
    )
    proc = run_git(worktree, ["rev-parse", "HEAD"])
    return proc.stdout.strip()


def delete_rejected_branch(repo: Path, branch_name: str) -> None:
    _ = run_git(repo, ["branch", "-D", branch_name], check=False)


def _commit_message(title: str) -> str:
    title = title.strip().rstrip(".") or "Forge autonomous improvement"
    lowered = title[:1].lower() + title[1:]
    if lowered.startswith(("add ", "fix ", "update ", "remove ", "document ", "refactor ")):
        summary = lowered
    else:
        summary = f"update {lowered}"
    return f"chore: {summary}"[:72]
