from collections.abc import Iterable, Iterator, Mapping, Sequence
from os import PathLike
from typing import override

class Error(Exception): ...
class DatabaseError(Error): ...
class IntegrityError(DatabaseError): ...
class OperationalError(DatabaseError): ...

type SqliteValue = str | int | float | bytes | None

class Row(Mapping[str, SqliteValue]):
    @override
    def __getitem__(self, key: str | int) -> SqliteValue: ...
    @override
    def __len__(self) -> int: ...
    @override
    def __iter__(self) -> Iterator[str]: ...

class Cursor(Iterator[Row]):
    @override
    def __iter__(self) -> Iterator[Row]: ...
    @override
    def __next__(self) -> Row: ...
    def execute(self, sql: str, parameters: Sequence[object] | Mapping[str, object] = ...) -> Cursor: ...
    def executemany(self, sql: str, seq_of_parameters: Iterable[Sequence[object] | Mapping[str, object]]) -> Cursor: ...
    def executescript(self, sql_script: str) -> Cursor: ...
    def fetchone(self) -> Row | None: ...
    def fetchall(self) -> list[Row]: ...
    @property
    def lastrowid(self) -> int | None: ...
    @property
    def rowcount(self) -> int: ...

class Connection:
    row_factory: object
    def execute(self, sql: str, parameters: Sequence[object] | Mapping[str, object] = ...) -> Cursor: ...
    def executemany(self, sql: str, seq_of_parameters: Iterable[Sequence[object] | Mapping[str, object]]) -> Cursor: ...
    def executescript(self, sql_script: str) -> Cursor: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...

def connect(
    database: str | bytes | PathLike[str] | PathLike[bytes],
    timeout: float = ...,
    detect_types: int = ...,
    isolation_level: str | None = ...,
    check_same_thread: bool = ...,
    factory: type[Connection] | None = ...,
    cached_statements: int = ...,
    uri: bool = ...,
) -> Connection: ...
